#!/usr/bin/env node
/*
BEISPIEL
*/

let x;  //Eine Variable namens x deklarieren

/*
AUFGABEN BEREICH
###############################################

Beschreibe die Art des Datentyps

###############################################
*/


x = 1;            - Ganzzahl (integer) // 
x = 0.01;         - Gleitkommazahl (float) //
x = "hello world";- Zeichenkette (string) //
x = 'JavaScript'; - Zeichenkette (string) //
x = true;         - Wahrheitswert (boolean)//
x = false;        - Wahrheitswert (boolean) //
x = null;         - Nullwert (null) //
x = undefined;    - Undefinierter Wert (undefined) //
