#!/usr/bin/env node

/* 
Operatoren agieren auf Werten (den Operanden), um einen neuen Wert zu erzeugen.
Arithmetische Operatoren gehören zu den einfachsten Operatoren:
*/
let opt;
3 + 2                      // => 5: Addition
3 - 2                      // => 1: Subtraktion
3 * 2                      // => 6: Multiplikation
3 / 2                      // => 1.5: Division
points[1].x - points[0].x  // => 1: Auch komplexere Operanden sind möglich.
"3" + "2"                  // => "32": + addiert Zahlen, verkettet Strings.

/* JavaScript bietet einige arithmetische Kurzoperatoren: */
let count = 0;             // Variable definieren.
count++;                   // Variable inkrementieren.
count--;                   // Variable dekrementieren.
count += 2;                // 2 addieren, entspricht count = count + 2;.
count *= 3;                // Mit 3 multiplizieren, entspricht count = count * 3;.
count                      // => 6: Variablennamen sind ebenfalls Ausdrücke.“

/*
AUFGABEN BEREICH
###############################################

Erstelle 5 unterschiedliche Mathematische Terme

###############################################
*/


