#!/usr/bin/env node

// Gleichheits- und Relationsoperatoren prüfen, ob zwei Werte gleich, ungleich,
// kleiner als, größer als usw. sind. Sie werden zu true oder false ausgewertet.
let x = 2, y = 3;          // Diese =-Zeichen sind Zuweisungen, keine
// Gleichheitstests.
x === y                    // => false: Gleichheit.
x !== y                    // => true: Ungleichheit.
x < y                      // => true: kleiner als.
x <= y                     // => true: kleiner als oder gleich.
x > y                      // => false: größer als.
x >= y                     // => false: größer als oder gleich.
"two" === "three"          // => false: Die beiden Strings sind verschieden.
"two" > "three"            // => true: "tw" ist alphabetisch größer als "th".
false === (x > y)          // => true: false ist gleich false.
// Logische Operatoren kombinieren oder invertieren boolesche Werte:
(x === 2) && (y === 3)     // => true: Beide Vergleiche sind wahr. && ist AND (UND).
(x > 3) || (y < 3)         // => false: Keiner der Vergleiche ist wahr.
// || ist OR (ODER).
!(x === y)                 // => true: ! invertiert einen booleschen Wert.

/*
AUFGABEN BEREICH
###############################################

Versuche eine Funktion zu schreiben
in der 2-3 Werte eines zuvor
erstellten Objekts verglichen werden.

zb. !!***(Psuedo-code)***!!
function compairCars (Auto1,Auto2)
{
    return
    (
        Auto1.Farbe == Auto2.Farbe &&
        Auto1.AnzahlTueren == Auto2.AnzahlTueren &&
        Auto1.Treibstoff != Auto2.Treibstoff
        )
}
      

###############################################
*/
const book = {name: "Duden", seiten: 5000, farbe: "blau"}

function Book(name, seiten, farbe) {
    this.name = name
    this.seiten = seiten
    this.farbe = farbe
}
const book2 = new Book("JavaSkript", 900, "weiß")
console.log(book)
console.log(book2)
function vergleich(book, book2) {
    return book.seiten > book2.seiten
    
}
const kleiner = vergleich(book, book2)
console.log(kleiner)